import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.defaulter': 'Defaulter Search & Tracking',
    'nav.riskDashboard': 'Risk Dashboard',
    'nav.individual': 'Individual Risk Assessment',
    'nav.synthetic': 'Synthetic Data Generator',
    'nav.howItWorks': 'How it Works',
    
    // Hero
    'hero.title1': 'Credit Risk Prediction',
    'hero.title2': 'Engine',
    'hero.subtitle': 'Predict Probability of Default using',
    'hero.subtitleHighlight': 'alternative behavioral signals',
    'hero.subtitleEnd': '. Upload your dataset and assess risk instantly with our AI-powered analytics.',
    'hero.getStarted': 'Get Started',
    'hero.howItWorks': 'How it works →',
    
    // Footer
    'footer.description': 'Advanced AI technology to predict credit risk and probability of default using alternative behavioral signals and real-time data analytics.',
    'footer.developers': 'Developers',
    'footer.aboutTech': 'About Our Technology',
    'footer.techDescription': 'The system performs automatic credit risk assessment using a pre-trained machine learning model. It loads behavioral data and financial indicators, processes the input variables, predicts default probability, combines risk factors with credit history, and converts the result to a comprehensive risk score.',
    'footer.contribute': 'Contribute on GitHub',
    'footer.rights': 'All rights reserved.',
    
    // Chatbot
    'chatbot.welcome': "Hello! I'm your CreditWise assistant. How can I help you with credit risk analysis today?",
    'chatbot.placeholder': 'Type your message...',
    'chatbot.typing': 'Typing...',
    'chatbot.unavailable': 'Chat temporarily unavailable. Please try again.',
    'chatbot.noResponse': "Sorry, I couldn't find that in CreditWise's context.",
    'chatbot.sources': 'Sources available',
    'chatbot.title': 'CreditWise Assistant',
    
    // Risk Dashboard
    'dashboard.title1': 'Risk Analysis',
    'dashboard.title2': 'Dashboard',
    'dashboard.subtitle': 'Track and analyze borrower risk over time with',
    'dashboard.subtitleHighlight': 'comprehensive trend analysis',
    'dashboard.subtitleEnd': ' and real-time risk monitoring.',
    'dashboard.viewDashboard': 'View Dashboard',
    'dashboard.pageTitle': 'Risk Analysis Dashboard',
    'dashboard.users': 'Users',
    'dashboard.rows': 'rows',
    'dashboard.columns': 'columns',
    'dashboard.user': 'User',
    'dashboard.lowRisk': 'Low Risk',
    'dashboard.mediumRisk': 'Medium Risk',
    'dashboard.highRisk': 'High Risk',
    'dashboard.latestPD': 'Latest PD Score',
    'dashboard.latestMonth': 'Latest Month',
    'dashboard.noData': 'No data available for this user',
    'dashboard.riskOverTime': 'Risk Over Time',
    'dashboard.all': 'All',
    'dashboard.sixMonths': '6 months',
    'dashboard.twelveMonths': '12 months',
    'dashboard.selectUser': 'Select a user to view risk analysis',
    'dashboard.chooseUser': 'Choose from the user list on the left',
    'dashboard.loadingUsers': 'Loading users...',
    'dashboard.loadingChart': 'Loading chart data...',
    
    // Individual Assessment
    'individual.title1': 'Individual Risk',
    'individual.title2': 'Assessment',
    'individual.subtitle': 'Analyze credit risk for individual borrowers using',
    'individual.subtitleHighlight': 'comprehensive behavioral data',
    'individual.subtitleEnd': ' and alternative signals for precise risk scoring.',
    'individual.startAssessment': 'Start Assessment',
    'individual.userRiskAssessment': 'User Risk Assessment',
    'individual.formDescription': 'Enter user details to perform real-time credit risk analysis. Our AI model will evaluate behavioral patterns and provide instant risk scoring.',
    'individual.rechargeFreq': 'Recharge Frequency',
    'individual.avgRechargeAmt': 'Average Recharge Amount',
    'individual.employmentType': 'Employment Type',
    'individual.employed': 'Employed',
    'individual.selfEmployed': 'Self Employed',
    'individual.unemployed': 'Unemployed',
    'individual.student': 'Student',
    'individual.retired': 'Retired',
    'individual.avgDaysLate': 'Average Days Late',
    'individual.paymentDelayRatio': 'Payment Delay Ratio',
    'individual.avgPaymentDue': 'Average Payment Due',
    'individual.paymentToDueRatio': 'Payment to Due Ratio',
    'individual.avgOrderValue': 'Average Order Value',
    'individual.returnRate': 'Return Rate',
    'individual.monthsActive': 'Months Active',
    'individual.geoVariance': 'Geo Variance Score',
    'individual.calculateRisk': 'Calculate Risk Score',
    'individual.calculating': 'Calculating Risk Score...',
    'individual.assessmentHistory': 'Assessment History',
    'individual.historyDescription': 'View and manage previous individual risk assessments.',
    'individual.downloadExcel': 'Download Excel',
    'individual.noAssessments': 'No assessments found. Start by creating your first individual assessment above.',
    'individual.riskScore': 'Risk Score',
    'individual.riskCategory': 'Risk Category',
    'individual.timestamp': 'Timestamp',
    'individual.required': 'is required',
    'individual.selectEmployment': 'Select employment type',
    
    // Synthetic Data
    'synthetic.title1': 'Synthetic Data',
    'synthetic.title2': 'Generator',
    'synthetic.subtitle': 'Upload CSV files with missing data and automatically fill empty cells with',
    'synthetic.subtitleHighlight': 'contextually appropriate synthetic values',
    'synthetic.subtitleEnd': ' for testing and development.',
    'synthetic.generateData': 'Generate Data',
    'synthetic.uploadCSV': 'Upload CSV File',
    'synthetic.uploadDescription': 'Upload a CSV or Excel file with missing data. Our AI will intelligently fill empty cells based on existing column patterns.',
    'synthetic.uploadFile': 'Upload your data file',
    'synthetic.supportsFormats': 'Supports CSV and Excel (.xlsx) formats',
    'synthetic.uploadBtn': 'Upload CSV',
    'synthetic.processData': 'Process Data',
    'synthetic.processing': 'Processing...',
    'synthetic.downloadProcessed': 'Download Processed Data',
    'synthetic.originalData': 'Original Data',
    'synthetic.processedData': 'Processed Data',
    'synthetic.empty': 'empty',
    'synthetic.scrollView': 'Scroll to view more →↓',
    
    // Defaulter Tracking
    'defaulter.title': 'Defaulter Search & Tracking',
    'defaulter.description': 'Upload your CSV, pick a user, and compute Probability of Default.',
    'defaulter.realtime': 'Real-time ready',
    'defaulter.uploadCSV': 'Upload CSV',
    'defaulter.loadDemo': 'Load Demo Data',
    'defaulter.downloadExcel': 'Download Excel',
    'defaulter.selectUser': 'Select User ID',
    'defaulter.loadData': 'Load data to select',
    'defaulter.analyzeRisk': 'Analyze Risk',
    'defaulter.analyzing': 'Analyzing...',
    'defaulter.loadPrompt': 'Load data and select a user to see their risk profile.',
    'defaulter.riskDashboard': 'Risk Assessment Dashboard',
    'defaulter.probabilityDefault': 'Probability of Default',
    'defaulter.keyMarkers': 'Key Behavioral Markers',
    'defaulter.paymentDelay': 'Payment Delay Ratio',
    'defaulter.cartAbandonment': 'Cart Abandonment Rate',
    'defaulter.geoVariance': 'Geo-variance Score',
    
    // Common
    'common.risk': 'Risk',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...'
  },
  es: {
    // Navigation
    'nav.defaulter': 'Búsqueda y Seguimiento de Morosos',
    'nav.riskDashboard': 'Panel de Riesgo',
    'nav.individual': 'Evaluación Individual de Riesgo',
    'nav.synthetic': 'Generador de Datos Sintéticos',
    'nav.howItWorks': 'Cómo Funciona',
    
    // Hero
    'hero.title1': 'Predicción de Riesgo Crediticio',
    'hero.title2': 'Motor',
    'hero.subtitle': 'Predecir la Probabilidad de Incumplimiento usando',
    'hero.subtitleHighlight': 'señales de comportamiento alternativas',
    'hero.subtitleEnd': '. Cargue su conjunto de datos y evalúe el riesgo instantáneamente con nuestro análisis impulsado por IA.',
    'hero.getStarted': 'Comenzar',
    'hero.howItWorks': 'Cómo funciona →',
    
    // Footer
    'footer.description': 'Tecnología avanzada de IA para predecir el riesgo crediticio y la probabilidad de incumplimiento utilizando señales de comportamiento alternativas y análisis de datos en tiempo real.',
    'footer.developers': 'Desarrolladores',
    'footer.aboutTech': 'Sobre Nuestra Tecnología',
    'footer.techDescription': 'El sistema realiza una evaluación automática del riesgo crediticio utilizando un modelo de aprendizaje automático preentrenado. Carga datos de comportamiento e indicadores financieros, procesa las variables de entrada, predice la probabilidad de incumplimiento, combina factores de riesgo con historial crediticio y convierte el resultado en una puntuación de riesgo integral.',
    'footer.contribute': 'Contribuir en GitHub',
    'footer.rights': 'Todos los derechos reservados.',
    
    // Chatbot
    'chatbot.welcome': '¡Hola! Soy tu asistente CreditWise. ¿Cómo puedo ayudarte con el análisis de riesgo crediticio hoy?',
    'chatbot.placeholder': 'Escribe tu mensaje...',
    'chatbot.typing': 'Escribiendo...',
    'chatbot.unavailable': 'Chat temporalmente no disponible. Por favor, inténtalo de nuevo.',
    'chatbot.noResponse': 'Lo siento, no pude encontrar eso en el contexto de CreditWise.',
    'chatbot.sources': 'Fuentes disponibles',
    'chatbot.title': 'Asistente CreditWise',
    
    // Risk Dashboard
    'dashboard.title1': 'Análisis de Riesgo',
    'dashboard.title2': 'Panel',
    'dashboard.subtitle': 'Rastree y analice el riesgo del prestatario a lo largo del tiempo con',
    'dashboard.subtitleHighlight': 'análisis de tendencias integral',
    'dashboard.subtitleEnd': ' y monitoreo de riesgo en tiempo real.',
    'dashboard.viewDashboard': 'Ver Panel',
    'dashboard.pageTitle': 'Panel de Análisis de Riesgo',
    'dashboard.users': 'Usuarios',
    'dashboard.rows': 'filas',
    'dashboard.columns': 'columnas',
    'dashboard.user': 'Usuario',
    'dashboard.lowRisk': 'Riesgo Bajo',
    'dashboard.mediumRisk': 'Riesgo Medio',
    'dashboard.highRisk': 'Riesgo Alto',
    'dashboard.latestPD': 'Puntuación PD Más Reciente',
    'dashboard.latestMonth': 'Mes Más Reciente',
    'dashboard.noData': 'No hay datos disponibles para este usuario',
    'dashboard.riskOverTime': 'Riesgo a lo Largo del Tiempo',
    'dashboard.all': 'Todo',
    'dashboard.sixMonths': '6 meses',
    'dashboard.twelveMonths': '12 meses',
    'dashboard.selectUser': 'Seleccione un usuario para ver el análisis de riesgo',
    'dashboard.chooseUser': 'Elija de la lista de usuarios a la izquierda',
    'dashboard.loadingUsers': 'Cargando usuarios...',
    'dashboard.loadingChart': 'Cargando datos del gráfico...',
    
    // Individual Assessment
    'individual.title1': 'Riesgo Individual',
    'individual.title2': 'Evaluación',
    'individual.subtitle': 'Analice el riesgo crediticio de prestatarios individuales usando',
    'individual.subtitleHighlight': 'datos de comportamiento integrales',
    'individual.subtitleEnd': ' y señales alternativas para puntuación de riesgo precisa.',
    'individual.startAssessment': 'Iniciar Evaluación',
    'individual.userRiskAssessment': 'Evaluación de Riesgo del Usuario',
    'individual.formDescription': 'Ingrese los detalles del usuario para realizar análisis de riesgo crediticio en tiempo real. Nuestro modelo de IA evaluará patrones de comportamiento y proporcionará puntuación de riesgo instantánea.',
    'individual.rechargeFreq': 'Frecuencia de Recarga',
    'individual.avgRechargeAmt': 'Monto Promedio de Recarga',
    'individual.employmentType': 'Tipo de Empleo',
    'individual.employed': 'Empleado',
    'individual.selfEmployed': 'Autónomo',
    'individual.unemployed': 'Desempleado',
    'individual.student': 'Estudiante',
    'individual.retired': 'Jubilado',
    'individual.avgDaysLate': 'Días Promedio de Retraso',
    'individual.paymentDelayRatio': 'Ratio de Retraso de Pago',
    'individual.avgPaymentDue': 'Pago Promedio Adeudado',
    'individual.paymentToDueRatio': 'Ratio de Pago a Vencido',
    'individual.avgOrderValue': 'Valor Promedio de Pedido',
    'individual.returnRate': 'Tasa de Retorno',
    'individual.monthsActive': 'Meses Activo',
    'individual.geoVariance': 'Puntuación de Varianza Geográfica',
    'individual.calculateRisk': 'Calcular Puntuación de Riesgo',
    'individual.calculating': 'Calculando Puntuación de Riesgo...',
    'individual.assessmentHistory': 'Historial de Evaluaciones',
    'individual.historyDescription': 'Ver y gestionar evaluaciones de riesgo individuales anteriores.',
    'individual.downloadExcel': 'Descargar Excel',
    'individual.noAssessments': 'No se encontraron evaluaciones. Comience creando su primera evaluación individual arriba.',
    'individual.riskScore': 'Puntuación de Riesgo',
    'individual.riskCategory': 'Categoría de Riesgo',
    'individual.timestamp': 'Marca de Tiempo',
    'individual.required': 'es requerido',
    'individual.selectEmployment': 'Seleccionar tipo de empleo',
    
    // Synthetic Data
    'synthetic.title1': 'Datos Sintéticos',
    'synthetic.title2': 'Generador',
    'synthetic.subtitle': 'Cargue archivos CSV con datos faltantes y llene automáticamente las celdas vacías con',
    'synthetic.subtitleHighlight': 'valores sintéticos contextualmente apropiados',
    'synthetic.subtitleEnd': ' para pruebas y desarrollo.',
    'synthetic.generateData': 'Generar Datos',
    'synthetic.uploadCSV': 'Cargar Archivo CSV',
    'synthetic.uploadDescription': 'Cargue un archivo CSV o Excel con datos faltantes. Nuestra IA llenará inteligentemente las celdas vacías basándose en patrones de columnas existentes.',
    'synthetic.uploadFile': 'Cargue su archivo de datos',
    'synthetic.supportsFormats': 'Soporta formatos CSV y Excel (.xlsx)',
    'synthetic.uploadBtn': 'Cargar CSV',
    'synthetic.processData': 'Procesar Datos',
    'synthetic.processing': 'Procesando...',
    'synthetic.downloadProcessed': 'Descargar Datos Procesados',
    'synthetic.originalData': 'Datos Originales',
    'synthetic.processedData': 'Datos Procesados',
    'synthetic.empty': 'vacío',
    'synthetic.scrollView': 'Desplácese para ver más →↓',
    
    // Defaulter Tracking
    'defaulter.title': 'Búsqueda y Seguimiento de Morosos',
    'defaulter.description': 'Cargue su CSV, elija un usuario y calcule la Probabilidad de Incumplimiento.',
    'defaulter.realtime': 'Listo en tiempo real',
    'defaulter.uploadCSV': 'Cargar CSV',
    'defaulter.loadDemo': 'Cargar Datos de Demostración',
    'defaulter.downloadExcel': 'Descargar Excel',
    'defaulter.selectUser': 'Seleccionar ID de Usuario',
    'defaulter.loadData': 'Cargar datos para seleccionar',
    'defaulter.analyzeRisk': 'Analizar Riesgo',
    'defaulter.analyzing': 'Analizando...',
    'defaulter.loadPrompt': 'Cargue datos y seleccione un usuario para ver su perfil de riesgo.',
    'defaulter.riskDashboard': 'Panel de Evaluación de Riesgo',
    'defaulter.probabilityDefault': 'Probabilidad de Incumplimiento',
    'defaulter.keyMarkers': 'Marcadores de Comportamiento Clave',
    'defaulter.paymentDelay': 'Ratio de Retraso de Pago',
    'defaulter.cartAbandonment': 'Tasa de Abandono de Carrito',
    'defaulter.geoVariance': 'Puntuación de Varianza Geográfica',
    
    // Common
    'common.risk': 'Riesgo',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.close': 'Cerrar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.loading': 'Cargando...'
  },
  fr: {
    // Navigation
    'nav.defaulter': 'Recherche et Suivi des Défaillants',
    'nav.riskDashboard': 'Tableau de Bord des Risques',
    'nav.individual': 'Évaluation Individuelle du Risque',
    'nav.synthetic': 'Générateur de Données Synthétiques',
    'nav.howItWorks': 'Comment ça Marche',
    
    // Hero
    'hero.title1': 'Prédiction du Risque de Crédit',
    'hero.title2': 'Moteur',
    'hero.subtitle': 'Prévoir la Probabilité de Défaut en utilisant',
    'hero.subtitleHighlight': 'des signaux comportementaux alternatifs',
    'hero.subtitleEnd': '. Téléchargez votre ensemble de données et évaluez le risque instantanément avec nos analyses alimentées par IA.',
    'hero.getStarted': 'Commencer',
    'hero.howItWorks': 'Comment ça marche →',
    
    // Footer
    'footer.description': 'Technologie d\'IA avancée pour prédire le risque de crédit et la probabilité de défaut en utilisant des signaux comportementaux alternatifs et des analyses de données en temps réel.',
    'footer.developers': 'Développeurs',
    'footer.aboutTech': 'À propos de Notre Technologie',
    'footer.techDescription': 'Le système effectue une évaluation automatique du risque de crédit en utilisant un modèle d\'apprentissage automatique pré-entraîné. Il charge les données comportementales et les indicateurs financiers, traite les variables d\'entrée, prédit la probabilité de défaut, combine les facteurs de risque avec l\'historique de crédit et convertit le résultat en un score de risque complet.',
    'footer.contribute': 'Contribuer sur GitHub',
    'footer.rights': 'Tous droits réservés.',
    
    // Chatbot
    'chatbot.welcome': 'Bonjour ! Je suis votre assistant CreditWise. Comment puis-je vous aider avec l\'analyse du risque de crédit aujourd\'hui ?',
    'chatbot.placeholder': 'Tapez votre message...',
    'chatbot.typing': 'En train d\'écrire...',
    'chatbot.unavailable': 'Chat temporairement indisponible. Veuillez réessayer.',
    'chatbot.noResponse': 'Désolé, je n\'ai pas pu trouver cela dans le contexte de CreditWise.',
    'chatbot.sources': 'Sources disponibles',
    'chatbot.title': 'Assistant CreditWise',
    
    // Risk Dashboard
    'dashboard.title1': 'Analyse des Risques',
    'dashboard.title2': 'Tableau de Bord',
    'dashboard.subtitle': 'Suivez et analysez le risque des emprunteurs au fil du temps avec',
    'dashboard.subtitleHighlight': 'une analyse complète des tendances',
    'dashboard.subtitleEnd': ' et une surveillance des risques en temps réel.',
    'dashboard.viewDashboard': 'Voir le Tableau de Bord',
    'dashboard.pageTitle': 'Tableau de Bord d\'Analyse des Risques',
    'dashboard.users': 'Utilisateurs',
    'dashboard.rows': 'lignes',
    'dashboard.columns': 'colonnes',
    'dashboard.user': 'Utilisateur',
    'dashboard.lowRisk': 'Risque Faible',
    'dashboard.mediumRisk': 'Risque Moyen',
    'dashboard.highRisk': 'Risque Élevé',
    'dashboard.latestPD': 'Score PD le Plus Récent',
    'dashboard.latestMonth': 'Mois le Plus Récent',
    'dashboard.noData': 'Aucune donnée disponible pour cet utilisateur',
    'dashboard.riskOverTime': 'Risque au Fil du Temps',
    'dashboard.all': 'Tout',
    'dashboard.sixMonths': '6 mois',
    'dashboard.twelveMonths': '12 mois',
    'dashboard.selectUser': 'Sélectionnez un utilisateur pour voir l\'analyse des risques',
    'dashboard.chooseUser': 'Choisissez dans la liste des utilisateurs à gauche',
    'dashboard.loadingUsers': 'Chargement des utilisateurs...',
    'dashboard.loadingChart': 'Chargement des données du graphique...',
    
    // Individual Assessment
    'individual.title1': 'Risque Individuel',
    'individual.title2': 'Évaluation',
    'individual.subtitle': 'Analysez le risque de crédit des emprunteurs individuels en utilisant',
    'individual.subtitleHighlight': 'des données comportementales complètes',
    'individual.subtitleEnd': ' et des signaux alternatifs pour une notation précise du risque.',
    'individual.startAssessment': 'Commencer l\'Évaluation',
    'individual.userRiskAssessment': 'Évaluation du Risque de l\'Utilisateur',
    'individual.formDescription': 'Entrez les détails de l\'utilisateur pour effectuer une analyse du risque de crédit en temps réel. Notre modèle d\'IA évaluera les modèles comportementaux et fournira une notation instantanée du risque.',
    'individual.rechargeFreq': 'Fréquence de Recharge',
    'individual.avgRechargeAmt': 'Montant Moyen de Recharge',
    'individual.employmentType': 'Type d\'Emploi',
    'individual.employed': 'Employé',
    'individual.selfEmployed': 'Travailleur Indépendant',
    'individual.unemployed': 'Sans Emploi',
    'individual.student': 'Étudiant',
    'individual.retired': 'Retraité',
    'individual.avgDaysLate': 'Jours Moyens de Retard',
    'individual.paymentDelayRatio': 'Ratio de Retard de Paiement',
    'individual.avgPaymentDue': 'Paiement Moyen Dû',
    'individual.paymentToDueRatio': 'Ratio Paiement sur Dû',
    'individual.avgOrderValue': 'Valeur Moyenne de Commande',
    'individual.returnRate': 'Taux de Retour',
    'individual.monthsActive': 'Mois Actifs',
    'individual.geoVariance': 'Score de Variance Géographique',
    'individual.calculateRisk': 'Calculer le Score de Risque',
    'individual.calculating': 'Calcul du Score de Risque...',
    'individual.assessmentHistory': 'Historique des Évaluations',
    'individual.historyDescription': 'Afficher et gérer les évaluations de risque individuelles précédentes.',
    'individual.downloadExcel': 'Télécharger Excel',
    'individual.noAssessments': 'Aucune évaluation trouvée. Commencez par créer votre première évaluation individuelle ci-dessus.',
    'individual.riskScore': 'Score de Risque',
    'individual.riskCategory': 'Catégorie de Risque',
    'individual.timestamp': 'Horodatage',
    'individual.required': 'est requis',
    'individual.selectEmployment': 'Sélectionner le type d\'emploi',
    
    // Synthetic Data
    'synthetic.title1': 'Données Synthétiques',
    'synthetic.title2': 'Générateur',
    'synthetic.subtitle': 'Téléchargez des fichiers CSV avec des données manquantes et remplissez automatiquement les cellules vides avec',
    'synthetic.subtitleHighlight': 'des valeurs synthétiques contextuellement appropriées',
    'synthetic.subtitleEnd': ' pour les tests et le développement.',
    'synthetic.generateData': 'Générer des Données',
    'synthetic.uploadCSV': 'Télécharger un Fichier CSV',
    'synthetic.uploadDescription': 'Téléchargez un fichier CSV ou Excel avec des données manquantes. Notre IA remplira intelligemment les cellules vides en fonction des modèles de colonnes existants.',
    'synthetic.uploadFile': 'Téléchargez votre fichier de données',
    'synthetic.supportsFormats': 'Prend en charge les formats CSV et Excel (.xlsx)',
    'synthetic.uploadBtn': 'Télécharger CSV',
    'synthetic.processData': 'Traiter les Données',
    'synthetic.processing': 'Traitement...',
    'synthetic.downloadProcessed': 'Télécharger les Données Traitées',
    'synthetic.originalData': 'Données Originales',
    'synthetic.processedData': 'Données Traitées',
    'synthetic.empty': 'vide',
    'synthetic.scrollView': 'Faites défiler pour voir plus →↓',
    
    // Defaulter Tracking
    'defaulter.title': 'Recherche et Suivi des Défaillants',
    'defaulter.description': 'Téléchargez votre CSV, choisissez un utilisateur et calculez la Probabilité de Défaut.',
    'defaulter.realtime': 'Prêt en temps réel',
    'defaulter.uploadCSV': 'Télécharger CSV',
    'defaulter.loadDemo': 'Charger des Données de Démonstration',
    'defaulter.downloadExcel': 'Télécharger Excel',
    'defaulter.selectUser': 'Sélectionner l\'ID Utilisateur',
    'defaulter.loadData': 'Charger des données pour sélectionner',
    'defaulter.analyzeRisk': 'Analyser le Risque',
    'defaulter.analyzing': 'Analyse...',
    'defaulter.loadPrompt': 'Chargez des données et sélectionnez un utilisateur pour voir son profil de risque.',
    'defaulter.riskDashboard': 'Tableau de Bord d\'Évaluation des Risques',
    'defaulter.probabilityDefault': 'Probabilité de Défaut',
    'defaulter.keyMarkers': 'Marqueurs Comportementaux Clés',
    'defaulter.paymentDelay': 'Ratio de Retard de Paiement',
    'defaulter.cartAbandonment': 'Taux d\'Abandon de Panier',
    'defaulter.geoVariance': 'Score de Variance Géographique',
    
    // Common
    'common.risk': 'Risque',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.loading': 'Chargement...'
  },
  de: {
    // Navigation
    'nav.defaulter': 'Zahlungsausfall-Suche & Verfolgung',
    'nav.riskDashboard': 'Risiko-Dashboard',
    'nav.individual': 'Individuelle Risikobewertung',
    'nav.synthetic': 'Synthetischer Datengenerator',
    'nav.howItWorks': 'Wie es Funktioniert',
    
    // Hero
    'hero.title1': 'Kreditrisiko-Vorhersage',
    'hero.title2': 'Motor',
    'hero.subtitle': 'Vorhersage der Ausfallwahrscheinlichkeit unter Verwendung',
    'hero.subtitleHighlight': 'alternativer Verhaltenssignale',
    'hero.subtitleEnd': '. Laden Sie Ihren Datensatz hoch und bewerten Sie das Risiko sofort mit unseren KI-gestützten Analysen.',
    'hero.getStarted': 'Jetzt Beginnen',
    'hero.howItWorks': 'Wie es funktioniert →',
    
    // Footer
    'footer.description': 'Fortschrittliche KI-Technologie zur Vorhersage des Kreditrisikos und der Ausfallwahrscheinlichkeit unter Verwendung alternativer Verhaltenssignale und Echtzeitdatenanalysen.',
    'footer.developers': 'Entwickler',
    'footer.aboutTech': 'Über Unsere Technologie',
    'footer.techDescription': 'Das System führt eine automatische Kreditrisikobewertung unter Verwendung eines vortrainierten maschinellen Lernmodells durch. Es lädt Verhaltensdaten und Finanzindikatoren, verarbeitet die Eingabevariablen, prognostiziert die Ausfallwahrscheinlichkeit, kombiniert Risikofaktoren mit Kredithistorie und wandelt das Ergebnis in einen umfassenden Risiko-Score um.',
    'footer.contribute': 'Auf GitHub beitragen',
    'footer.rights': 'Alle Rechte vorbehalten.',
    
    // Chatbot
    'chatbot.welcome': 'Hallo! Ich bin Ihr CreditWise-Assistent. Wie kann ich Ihnen heute bei der Kreditrisikoanalyse helfen?',
    'chatbot.placeholder': 'Geben Sie Ihre Nachricht ein...',
    'chatbot.typing': 'Schreibt...',
    'chatbot.unavailable': 'Chat vorübergehend nicht verfügbar. Bitte versuchen Sie es erneut.',
    'chatbot.noResponse': 'Entschuldigung, ich konnte das nicht im CreditWise-Kontext finden.',
    'chatbot.sources': 'Quellen verfügbar',
    'chatbot.title': 'CreditWise-Assistent',
    
    // Risk Dashboard
    'dashboard.title1': 'Risikoanalyse',
    'dashboard.title2': 'Dashboard',
    'dashboard.subtitle': 'Verfolgen und analysieren Sie das Kreditnehmerrisiko im Zeitverlauf mit',
    'dashboard.subtitleHighlight': 'umfassender Trendanalyse',
    'dashboard.subtitleEnd': ' und Echtzeitrisikoüberwachung.',
    'dashboard.viewDashboard': 'Dashboard Anzeigen',
    'dashboard.pageTitle': 'Risikoanalyse-Dashboard',
    'dashboard.users': 'Benutzer',
    'dashboard.rows': 'Zeilen',
    'dashboard.columns': 'Spalten',
    'dashboard.user': 'Benutzer',
    'dashboard.lowRisk': 'Niedriges Risiko',
    'dashboard.mediumRisk': 'Mittleres Risiko',
    'dashboard.highRisk': 'Hohes Risiko',
    'dashboard.latestPD': 'Neuester PD-Score',
    'dashboard.latestMonth': 'Neuester Monat',
    'dashboard.noData': 'Keine Daten für diesen Benutzer verfügbar',
    'dashboard.riskOverTime': 'Risiko im Zeitverlauf',
    'dashboard.all': 'Alle',
    'dashboard.sixMonths': '6 Monate',
    'dashboard.twelveMonths': '12 Monate',
    'dashboard.selectUser': 'Wählen Sie einen Benutzer, um die Risikoanalyse anzuzeigen',
    'dashboard.chooseUser': 'Wählen Sie aus der Benutzerliste links',
    'dashboard.loadingUsers': 'Benutzer werden geladen...',
    'dashboard.loadingChart': 'Diagrammdaten werden geladen...',
    
    // Individual Assessment
    'individual.title1': 'Individuelles Risiko',
    'individual.title2': 'Bewertung',
    'individual.subtitle': 'Analysieren Sie das Kreditrisiko einzelner Kreditnehmer unter Verwendung',
    'individual.subtitleHighlight': 'umfassender Verhaltensdaten',
    'individual.subtitleEnd': ' und alternativer Signale für präzise Risikobewertung.',
    'individual.startAssessment': 'Bewertung Starten',
    'individual.userRiskAssessment': 'Benutzerrisikobewertung',
    'individual.formDescription': 'Geben Sie Benutzerdetails ein, um eine Echtzeit-Kreditrisikoanalyse durchzuführen. Unser KI-Modell bewertet Verhaltensmuster und liefert sofortige Risikobewertung.',
    'individual.rechargeFreq': 'Aufladehäufigkeit',
    'individual.avgRechargeAmt': 'Durchschnittlicher Aufladebetrag',
    'individual.employmentType': 'Beschäftigungsart',
    'individual.employed': 'Angestellt',
    'individual.selfEmployed': 'Selbstständig',
    'individual.unemployed': 'Arbeitslos',
    'individual.student': 'Student',
    'individual.retired': 'Rentner',
    'individual.avgDaysLate': 'Durchschnittliche Verspätungstage',
    'individual.paymentDelayRatio': 'Zahlungsverzögerungsverhältnis',
    'individual.avgPaymentDue': 'Durchschnittliche Fälligkeit',
    'individual.paymentToDueRatio': 'Verhältnis Zahlung zu Fälligkeit',
    'individual.avgOrderValue': 'Durchschnittlicher Bestellwert',
    'individual.returnRate': 'Rücksendequote',
    'individual.monthsActive': 'Aktive Monate',
    'individual.geoVariance': 'Geo-Varianz-Score',
    'individual.calculateRisk': 'Risiko-Score Berechnen',
    'individual.calculating': 'Risiko-Score wird berechnet...',
    'individual.assessmentHistory': 'Bewertungshistorie',
    'individual.historyDescription': 'Frühere individuelle Risikobewertungen anzeigen und verwalten.',
    'individual.downloadExcel': 'Excel Herunterladen',
    'individual.noAssessments': 'Keine Bewertungen gefunden. Beginnen Sie mit Ihrer ersten individuellen Bewertung oben.',
    'individual.riskScore': 'Risiko-Score',
    'individual.riskCategory': 'Risikokategorie',
    'individual.timestamp': 'Zeitstempel',
    'individual.required': 'ist erforderlich',
    'individual.selectEmployment': 'Beschäftigungsart auswählen',
    
    // Synthetic Data
    'synthetic.title1': 'Synthetische Daten',
    'synthetic.title2': 'Generator',
    'synthetic.subtitle': 'Laden Sie CSV-Dateien mit fehlenden Daten hoch und füllen Sie leere Zellen automatisch mit',
    'synthetic.subtitleHighlight': 'kontextgerecht geeigneten synthetischen Werten',
    'synthetic.subtitleEnd': ' für Tests und Entwicklung.',
    'synthetic.generateData': 'Daten Generieren',
    'synthetic.uploadCSV': 'CSV-Datei Hochladen',
    'synthetic.uploadDescription': 'Laden Sie eine CSV- oder Excel-Datei mit fehlenden Daten hoch. Unsere KI füllt intelligenterweise leere Zellen basierend auf bestehenden Spaltenmustern.',
    'synthetic.uploadFile': 'Laden Sie Ihre Datendatei hoch',
    'synthetic.supportsFormats': 'Unterstützt CSV- und Excel-Formate (.xlsx)',
    'synthetic.uploadBtn': 'CSV Hochladen',
    'synthetic.processData': 'Daten Verarbeiten',
    'synthetic.processing': 'Verarbeitung...',
    'synthetic.downloadProcessed': 'Verarbeitete Daten Herunterladen',
    'synthetic.originalData': 'Originaldaten',
    'synthetic.processedData': 'Verarbeitete Daten',
    'synthetic.empty': 'leer',
    'synthetic.scrollView': 'Scrollen Sie, um mehr zu sehen →↓',
    
    // Defaulter Tracking
    'defaulter.title': 'Zahlungsausfall-Suche & Verfolgung',
    'defaulter.description': 'Laden Sie Ihre CSV hoch, wählen Sie einen Benutzer und berechnen Sie die Ausfallwahrscheinlichkeit.',
    'defaulter.realtime': 'Echtzeitbereit',
    'defaulter.uploadCSV': 'CSV Hochladen',
    'defaulter.loadDemo': 'Demodaten Laden',
    'defaulter.downloadExcel': 'Excel Herunterladen',
    'defaulter.selectUser': 'Benutzer-ID Auswählen',
    'defaulter.loadData': 'Daten laden zum Auswählen',
    'defaulter.analyzeRisk': 'Risiko Analysieren',
    'defaulter.analyzing': 'Analysiere...',
    'defaulter.loadPrompt': 'Laden Sie Daten und wählen Sie einen Benutzer, um sein Risikoprofil zu sehen.',
    'defaulter.riskDashboard': 'Risikobewertungs-Dashboard',
    'defaulter.probabilityDefault': 'Ausfallwahrscheinlichkeit',
    'defaulter.keyMarkers': 'Wichtige Verhaltensmarker',
    'defaulter.paymentDelay': 'Zahlungsverzögerungsverhältnis',
    'defaulter.cartAbandonment': 'Warenkorbabbruchrate',
    'defaulter.geoVariance': 'Geo-Varianz-Score',
    
    // Common
    'common.risk': 'Risiko',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.close': 'Schließen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.loading': 'Wird geladen...'
  },
  zh: {
    // Navigation
    'nav.defaulter': '违约者搜索与跟踪',
    'nav.riskDashboard': '风险仪表板',
    'nav.individual': '个人风险评估',
    'nav.synthetic': '合成数据生成器',
    'nav.howItWorks': '工作原理',
    
    // Hero
    'hero.title1': '信用风险预测',
    'hero.title2': '引擎',
    'hero.subtitle': '使用',
    'hero.subtitleHighlight': '替代行为信号',
    'hero.subtitleEnd': '预测违约概率。上传您的数据集，通过我们的AI驱动分析即时评估风险。',
    'hero.getStarted': '开始使用',
    'hero.howItWorks': '工作原理 →',
    
    // Footer
    'footer.description': '先进的AI技术，使用替代行为信号和实时数据分析预测信用风险和违约概率。',
    'footer.developers': '开发者',
    'footer.aboutTech': '关于我们的技术',
    'footer.techDescription': '该系统使用预训练的机器学习模型执行自动信用风险评估。它加载行为数据和财务指标，处理输入变量，预测违约概率，结合信用历史的风险因素，并将结果转换为综合风险评分。',
    'footer.contribute': '在GitHub上贡献',
    'footer.rights': '版权所有。',
    
    // Chatbot
    'chatbot.welcome': '您好！我是您的CreditWise助手。今天我可以如何帮助您进行信用风险分析？',
    'chatbot.placeholder': '输入您的消息...',
    'chatbot.typing': '正在输入...',
    'chatbot.unavailable': '聊天暂时不可用。请再试一次。',
    'chatbot.noResponse': '抱歉，我在CreditWise的上下文中找不到相关信息。',
    'chatbot.sources': '可用来源',
    'chatbot.title': 'CreditWise助手',
    
    // Risk Dashboard
    'dashboard.title1': '风险分析',
    'dashboard.title2': '仪表板',
    'dashboard.subtitle': '通过',
    'dashboard.subtitleHighlight': '综合趋势分析',
    'dashboard.subtitleEnd': '和实时风险监控跟踪和分析借款人风险。',
    'dashboard.viewDashboard': '查看仪表板',
    'dashboard.pageTitle': '风险分析仪表板',
    'dashboard.users': '用户',
    'dashboard.rows': '行',
    'dashboard.columns': '列',
    'dashboard.user': '用户',
    'dashboard.lowRisk': '低风险',
    'dashboard.mediumRisk': '中等风险',
    'dashboard.highRisk': '高风险',
    'dashboard.latestPD': '最新PD分数',
    'dashboard.latestMonth': '最新月份',
    'dashboard.noData': '该用户没有可用数据',
    'dashboard.riskOverTime': '随时间变化的风险',
    'dashboard.all': '全部',
    'dashboard.sixMonths': '6个月',
    'dashboard.twelveMonths': '12个月',
    'dashboard.selectUser': '选择用户查看风险分析',
    'dashboard.chooseUser': '从左侧用户列表中选择',
    'dashboard.loadingUsers': '加载用户中...',
    'dashboard.loadingChart': '加载图表数据中...',
    
    // Individual Assessment
    'individual.title1': '个人风险',
    'individual.title2': '评估',
    'individual.subtitle': '使用',
    'individual.subtitleHighlight': '综合行为数据',
    'individual.subtitleEnd': '和替代信号分析个别借款人的信用风险，以实现精确的风险评分。',
    'individual.startAssessment': '开始评估',
    'individual.userRiskAssessment': '用户风险评估',
    'individual.formDescription': '输入用户详细信息以执行实时信用风险分析。我们的AI模型将评估行为模式并提供即时风险评分。',
    'individual.rechargeFreq': '充值频率',
    'individual.avgRechargeAmt': '平均充值金额',
    'individual.employmentType': '就业类型',
    'individual.employed': '受雇',
    'individual.selfEmployed': '自雇',
    'individual.unemployed': '失业',
    'individual.student': '学生',
    'individual.retired': '退休',
    'individual.avgDaysLate': '平均延迟天数',
    'individual.paymentDelayRatio': '付款延迟比率',
    'individual.avgPaymentDue': '平均应付款',
    'individual.paymentToDueRatio': '付款与应付比率',
    'individual.avgOrderValue': '平均订单价值',
    'individual.returnRate': '退货率',
    'individual.monthsActive': '活跃月数',
    'individual.geoVariance': '地理变异分数',
    'individual.calculateRisk': '计算风险分数',
    'individual.calculating': '正在计算风险分数...',
    'individual.assessmentHistory': '评估历史',
    'individual.historyDescription': '查看和管理以前的个人风险评估。',
    'individual.downloadExcel': '下载Excel',
    'individual.noAssessments': '未找到评估。从上方创建您的第一个个人评估开始。',
    'individual.riskScore': '风险分数',
    'individual.riskCategory': '风险类别',
    'individual.timestamp': '时间戳',
    'individual.required': '是必需的',
    'individual.selectEmployment': '选择就业类型',
    
    // Synthetic Data
    'synthetic.title1': '合成数据',
    'synthetic.title2': '生成器',
    'synthetic.subtitle': '上传缺少数据的CSV文件，并自动用',
    'synthetic.subtitleHighlight': '上下文适当的合成值',
    'synthetic.subtitleEnd': '填充空单元格以进行测试和开发。',
    'synthetic.generateData': '生成数据',
    'synthetic.uploadCSV': '上传CSV文件',
    'synthetic.uploadDescription': '上传缺少数据的CSV或Excel文件。我们的AI将根据现有列模式智能填充空单元格。',
    'synthetic.uploadFile': '上传您的数据文件',
    'synthetic.supportsFormats': '支持CSV和Excel（.xlsx）格式',
    'synthetic.uploadBtn': '上传CSV',
    'synthetic.processData': '处理数据',
    'synthetic.processing': '处理中...',
    'synthetic.downloadProcessed': '下载已处理的数据',
    'synthetic.originalData': '原始数据',
    'synthetic.processedData': '已处理数据',
    'synthetic.empty': '空',
    'synthetic.scrollView': '滚动查看更多 →↓',
    
    // Defaulter Tracking
    'defaulter.title': '违约者搜索与跟踪',
    'defaulter.description': '上传您的CSV，选择用户，并计算违约概率。',
    'defaulter.realtime': '实时准备就绪',
    'defaulter.uploadCSV': '上传CSV',
    'defaulter.loadDemo': '加载演示数据',
    'defaulter.downloadExcel': '下载Excel',
    'defaulter.selectUser': '选择用户ID',
    'defaulter.loadData': '加载数据以选择',
    'defaulter.analyzeRisk': '分析风险',
    'defaulter.analyzing': '分析中...',
    'defaulter.loadPrompt': '加载数据并选择用户以查看其风险档案。',
    'defaulter.riskDashboard': '风险评估仪表板',
    'defaulter.probabilityDefault': '违约概率',
    'defaulter.keyMarkers': '关键行为标记',
    'defaulter.paymentDelay': '付款延迟比率',
    'defaulter.cartAbandonment': '购物车放弃率',
    'defaulter.geoVariance': '地理变异分数',
    
    // Common
    'common.risk': '风险',
    'common.yes': '是',
    'common.no': '否',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.loading': '加载中...'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
